import emilyProfilePic from "../../public/emilyProfilePic.jpeg";

export const currentUserData = {
  universityEmail: "eh3244@nyu.edu",
  firstName: "Emily",
  lastName: "Han",
  picture: emilyProfilePic,
  year: "3",
  university: "New York University",
  major: "Computer Science",
  courses: [{courseNumber: "CSCI-UA202", courseName: "Operating Systems", 
    assignments: [{id: 1, name: "Lab 1", due: "2025-09-12"}, 
      {id: 2, name: "Lab 2", due:"2025-09-26"}, 
      {id: 3, name: "Lab 3", due:"2025-10-10"}, 
      {id: 4, name:"Lab 4", due:"2025-11-10"}, 
      {id: 5, name: "Lab 5", due: "2025-12-14"}], 
    studysets: [{id: 1, name:"Midterm"}, {id: 2, name:"Final"}], 
    notes: [{id: 1, name:"Quiz 1"}, {id:2, name:"Quiz 2"}, {id: 3, name:"Quiz 3"}, {id: 4, name:"Quiz 4"}, {id: 5, name:"Quiz 5"}, {id:6, name:"Quiz 6"}, {id: 7, name:"Quiz 7"}, {id:8, name:"Quiz 8"}, {id:9, name:"Quiz 9"}, {id:10, name:"Quiz 10"}]},
    {courseNumber: "MKTG-UB_1", courseName: "Intro To Marketing", 
      assignments: [ 
        {id: 1, name:"Group Project Proposal", due: "2025-09-15"}, 
        {id: 2, name: "Marketing Current Events Presentation", due: "2025-10-01"},
        {id: 3, name: "Group Project Situation Analysis", due: "2025-10-30" }, 
        {id: 4, name: "Group Project Marketing Analysis", due: "2025-12-03"}, 
        {id: 5, name: "Group Project Presentation", due: "2025-12-03"}], 
      studysets: [{id: 1, name: "Final"}], 
      notes: [{id: 1, name:"Dunlop Livery Antiques In-Class Case Quiz"},
        {id: 2, name: "Pintura Corporation In-Class Case Quiz"}, 
        {id: 3, name: "Virgin Mobile In-Class Case Quiz"}, 
        {id: 4, name: "Sagacity Tea In-Class Case Quiz"}, 
        {id: 5, name: "Sephora Direct In-Class Case Quiz"}]},
   {courseNumber: "CAMS-UA110", courseName: "Science Of Happiness", 
      assignments: [
        {id: 1,name: "Assignment #1: Initial Thoughts", due: "2025-09-05"}, 
        {id: 2, name: "Assignment #2: VIA Character Strengths", due: "2025-09-12"},
        {id: 3, name:"Assignment #3: Other People Matter", due: "2025-09-19"},
        {id: 4, name: "Assignment #4: Stages of Change", due: "2025-09-26"},
        {id: 5, name: "Assignment #5: Three Good Things", due: "2025-10-03"},
        {id: 6, name: "Response Paper 1", due: "2025-10-10" },
        {id: 7, name: "Assignment #6: Decision Making", due: "2025-10-10"}, 
        {id: 8, name: "Assignment #7: CBT", due: "2025-10-17"},
        {id: 9, name: "Assignment #8: Sleep, Movement, Mood", due: "2025-10-24"}, 
        {id: 10, name: "Assignment #9: Technology", due: "2025-11-01"},
        {id: 11, name:"Assignment #10: Gratitude", due: "2025-11-08"},
        {id: 12, name: "Response Paper 2", due: "2025-11-15"},
        {id: 13, name: "Assignment #11: PREP", due: "2025-11-15"},], 
      studysets: [{id: 1, name: "Final"}], 
      notes: [{id: 1, name: "Wellbeing Fall 2025"}, 
        {id: 2, name: "Positive Emotions Fall 2025"}, 
        {id: 3, name:"Relationships Fall 2025"}, 
        {id: 4, name:"Character Strengths Fall 2025"},
        {id: 5, name: "Plasticity Fall 2025"}, 
        {id: 6, name: "CBT I"}, 
        {id: 7, name: "CBT II"}],
    },
  ],
  sessionsAttended: [], //Roomids
};