export const subjectOptions = [
        {name: ""},
        {name: "Anything"},
        {name: "Accounting"},
        {name: "Anatomy"},
        {name: "Biology"},
        {name: "Chemistry"},
        {name: "Computer Science"},
        {name: "Data Science"},
        {name: "Economics"},
        {name: "Engineering"},
        {name: "Finance"},
        {name: "Film"},
        {name: "Investment Banking"},
        {name: "Marketing"},
        {name: "Math"},
        {name: "Medicine"},
        {name: "Nursing"},
        {name: "Philosophy"},
        {name: "Psychology"},
        {name: "Writing"},
    ]